name: GitLeak

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: gitleaks/gitleaks-action@v2
        name: Leak Scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
